export const brands = [
  {name: 'agip', image: require('../../../assets/image/fuelStations/brands/agip.png')},
  {name: 'aral', image: require('../../../assets/image/fuelStations/brands/aral.png')},
  {name: 'avia', image: require('../../../assets/image/fuelStations/brands/avia.png')},
  {name: 'baywa', image: require('../../../assets/image/fuelStations/brands/baywa.png')},
  {name: 'bft', image: require('../../../assets/image/fuelStations/brands/bft.png')},
  {name: 'classic', image: require('../../../assets/image/fuelStations/brands/classic.png')},
  {name: 'ed', image: require('../../../assets/image/fuelStations/brands/ed.png')},
  {name: 'elan', image: require('../../../assets/image/fuelStations/brands/elan.jpg')},
  {name: 'esso', image: require('../../../assets/image/fuelStations/brands/esso.png')},
  {name: 'go', image: require('../../../assets/image/fuelStations/brands/go.jpg')},
  {name: 'hem', image: require('../../../assets/image/fuelStations/brands/hem.jpg')},
  {name: 'hoyer', image: require('../../../assets/image/fuelStations/brands/hoyer.jpg')},
  {name: 'jet', image: require('../../../assets/image/fuelStations/brands/jet.png')},
  {name: 'markant', image: require('../../../assets/image/fuelStations/brands/markant.png')},
  {name: 'oil', image: require('../../../assets/image/fuelStations/brands/oil.jpg')},
  {name: 'omv', image: require('../../../assets/image/fuelStations/brands/omv.jpg')},
  {name: 'q1', image: require('../../../assets/image/fuelStations/brands/q1.png')},
  {name: 'raiffeisen', image: require('../../../assets/image/fuelStations/brands/raiffeisen.png')},
  {name: 'shell', image: require('../../../assets/image/fuelStations/brands/shell.png')},
  {name: 'sprint', image: require('../../../assets/image/fuelStations/brands/sprint.jpg')},
  {name: 'star', image: require('../../../assets/image/fuelStations/brands/star.jpg')},
  {name: 'team', image: require('../../../assets/image/fuelStations/brands/team.jpg')},
  {name: 'total', image: require('../../../assets/image/fuelStations/brands/total.png')},
  {name: 'westfalen', image: require('../../../assets/image/fuelStations/brands/westfalen.png')},
];